version: '3'
services:
  db:
    image: mysql
    ports:
      - "5432"
    environment:
      - MYSQL_DATABASE=SIGS_development
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'

  web:
    build: .
    command: /bin/bash -l -c "chmod +x start-dev.sh && ./start-dev.sh"
    volumes:
      - ./SIGS:/SIGS-MES
      - ./start-dev.sh:/SIGS-MES/start-dev.sh
    ports:
      - "3000:3000"
    links:
      - db:mysql
    depends_on:
      - db
